name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  cleanup: 
    uses: ./.github/workflows/cleanup.yml

  build-and-test:
    runs-on: ubuntu-4core-150g-ssd 
    needs: 
      - cleanup 

    steps:
    - uses: actions/checkout@v5

    - name: Building Docker images
      run: |
           docker build -f Dockerfile -t openfold-base . 
           docker build -f openfold3/tests/Dockerfile -t openfold-test .

    - name: Run unit tests
      run: docker run -v ${{ github.workspace }}/resources:/opt/openfold3/openfold3/resources openfold-test:latest pytest openfold3/tests
